### ISSUE TITLE
feat: scroll last scoreboard page partially

### ISSUE THREAD

**Issue by lperovskaya** [icpc/live-v3#32]
To make scoreboards with little remainder nicer, we can just scroll the last scoreboard page for the remaining number of lines. Will look super nice for two-page scoreboards

**Comment by irdkwmnsb** [comment]
@kunyavskiy suggested we don't scroll the last page partially but instead find such a number of rows to scroll each page so the last transition is not significantly smaller than the other.
Example:
If we have a scoreboard of 104 teams and a single page holds 25 rows instead of pages with rows from 
1 - 25, 26 - 50, 51 - 75, 76- 100, 101 - 104
we would show
1 - 25, 22 - 46, 42 - 66, 62 - 86, 83 - 104

**Comment by irdkwmnsb** [comment]
Done in 91a28a6116ccc0c79c3b8748184af2507dedbe1e
